version: 2.1
orbs:
  architect: giantswarm/architect@4.35.5

workflows:
  version: 2
  build:
    jobs:
    - architect/push-to-app-catalog:
        context: architect
        name: push-to-default-app-catalog
        executor: app-build-suite
        app_catalog: default-catalog
        app_catalog_test: default-test-catalog
        chart: prometheus-blackbox-exporter
        filters:
          tags:
            only: /^v.*/
          branches:
            only: /.*/
